---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Test template to demonstrate plugin issue'

Resources:
  dnsRecordLoadBalancer:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: "mydomain.example.com"
      Name: "mydomain.example.com"
      ResourceRecords:
        - "other-domain.example.com"
      Type: CNAME
