openapi: "3.0.0"
info:
  title: "parent-modules API"
  description: "parent-modules API"
  version: "1.0.0"
servers:
  - url: "https://"
paths:
  /customers:
    get:
      summary: "GET customers"
      responses:
        200:
          description: "OK"
  /customers/{customerId}:
    get:
      summary: "GET customers/{customerId}"
      parameters:
        - name: "customerId"
          in: "path"
      responses:
        200:
          description: "OK"